### ISSUE TITLE
建议：提供onload，scrollTo部分函数能力

### ISSUE THREAD

**Issue by xygengcn** [phphe/virtual-list#1]
希望能添加有以下能力

- 提供滚动到底和滚动到顶的函数回调 onload
- 提供跳转到底和滚动到顶的函数，以及跳转到某一条的能力。例如： scrollTo(0) 和 scrollToIndex()

**Comment by phphe** [comment]
建议尝试其他更成熟的库。这个库是为了he-tree开发的。我不计划增加新的功能。
